[project]
WORKDIR = "./dist/"
FILE = "2023.json"
AUTO_SAVE = 0
AUTO_SAVE_DIR = "./dist/"
STEP = 20
LIMIT = 30000
SLEEP_TIME = 0.5
MAX_RETRY = 5
SEARCH_OFFSET = 0

[qzone]
UIN = 1399896037
NICKNAME = "上海电力大学表白墙"
COOKIES = ""
AUTO_UPDATE = false
AUTO_UPDATE_HEADLESS = false
AUTO_UPDATE_FORCE = false
AUTO_UPDATE_USER = ""
AUTO_UPDATE_PASS = ""

[paddleocr]
USE_GPU = false
USE_MP = true
TOTAL_PROCESS_NUM = 2
