[project]
WORKDIR = "./dist/"
FILE = "2023.json"
AUTO_SAVE = 10
AUTO_SAVE_DIR = "/tmp/"
STEP = 20
LIMIT = 30000
SLEEP_TIME = 0.5
MAX_RETRY = 5
SEARCH_OFFSET = 0

[qzone]
UIN = 1399896037
NICKNAME = "上海电力大学表白墙"
COOKIES = ""

[paddleocr]
USE_GPU = false
USE_MP = false
TOTAL_PROCESS_NUM = 1
