name: Daily update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *" # Every day at 01:00 UTC (09:00 CST)
    - cron: "0 6 * * *" # Every day at 06:00 UTC (14:00 CST)
    - cron: "0 11 * * *" # Every day at 11:00 UTC (19:00 CST)
    - cron: "0 16 * * *" # Every day at 16:00 UTC (00:00 CST)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Checkout dist
        uses: actions/checkout@v3
        with:
          ref: dist
          path: dist

      - name: Cache PaddleOCR
        uses: actions/cache@v3
        with:
          path: ~/.paddleocr
          key: ${{ runner.os }}-paddleocr-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-paddleocr-

      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@v2

      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --with ci

      - name: Add config
        run: |
          cat > config.toml << "EOF"
          ${{ secrets.CONFIG }}
          EOF

      - name: Set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Setup v2ray
        uses: TeamSUEP/setup-v2ray@v2
        with:
          config: ${{ secrets.V2RAY_CONFIG }}

      - name: Update messages
        id: download
        run: poetry run python main.py --new

      - name: Save config to GitHub secret
        run: poetry run python update_github_secret.py

      - name: Add & Commit changes
        if: "${{ steps.download.outputs.messagesAdded != 0 }}"
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./dist/"
          default_author: github_actions
          message: "Update ${{ steps.download.outputs.messagesAdded }} new messages"
